# Generated by Django 3.0.6 on 2021-04-14 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entrada', models.PositiveIntegerField(default=0)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('lote_del_producto', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'LOTES',
                'verbose_name_plural': 'LOTE',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('proveedor', models.CharField(max_length=30)),
                ('registro_invima', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=30, null=True)),
                ('presentacion', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('MEDICAMENTO', 'MEDICAMENTO'), ('ASEO', 'ELEMENTO DE ASEO'), ('INSUMO', 'PRODUCTO E INSUMO'), ('EQUIPO', 'EQUIPO'), ('SEGURIDAD Y SALUD EN EL TRABAJO', 'SEGURIDAD Y SALUD EN EL TRABAJO')], default='MEDICAMENTO', max_length=100)),
            ],
            options={
                'verbose_name': 'ARTÍCULOS',
                'verbose_name_plural': 'ARTÍCULO',
            },
        ),
        migrations.CreateModel(
            name='SalidaLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField(auto_now_add=True)),
                ('cantidad_salida', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Lote')),
            ],
            options={
                'verbose_name': 'LOTES SALIDA',
                'verbose_name_plural': 'LOTE SALIDA',
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Producto'),
        ),
        migrations.CreateModel(
            name='EntradaLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('cantidad_entrante', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Lote')),
            ],
            options={
                'verbose_name': 'LOTES ENTRADA',
                'verbose_name_plural': 'LOTE ENTRADA',
            },
        ),
    ]
