# Generated by Django 3.0.6 on 2021-06-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lote',
            name='fecha_eliminacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_eliminacion',
            field=models.DateField(null=True),
        ),
    ]
