# Generated by Django 3.0.6 on 2021-06-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20210610_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='eliminado',
            field=models.BooleanField(default=True),
        ),
    ]
